/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/range-rover-evoque-1bc1e752f8e24fc7bd277e1eb5cee2ee
title: Range Rover Evoque
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame , useThree } from '@react-three/fiber'
import { useSpring, a } from '@react-spring/three'
import * as THREE from 'three'

export default function Model(props) {
  const {sectionID} = props;
  const group = useRef();
  const wheel1 = useRef();
  const wheel2 = useRef();
  const wheel3 = useRef();
  const wheel4 = useRef();

  const camera = useThree((state) => state.camera);

  useFrame((state)=>{
    const t = state.clock.getElapsedTime();
    wheel1.current.rotation.x = sectionID < 3 && t * 5 * Math.PI;
    wheel2.current.rotation.x = sectionID < 3 && t * 5 * Math.PI;
    wheel3.current.rotation.x = sectionID < 3 && t * 5 * Math.PI;
    wheel4.current.rotation.x =  sectionID < 3 && t * 5 * Math.PI;
    sectionID === 4 ? camera.position.lerp(new THREE.Vector3(-5,2,8),0.025):camera.position.lerp(new THREE.Vector3(-5,0.5,8),0.025);
  });
  const carAnimation = useSpring({
      rotation: sectionID === 1 ? [0,0,0] : [0,0.2,0]
  });
  console.log(carAnimation)
  const { nodes, materials } = useGLTF('../../car/scene.gltf')
  
  
  return (
    <a.group ref={group} {...props} dispose={null} rotation={carAnimation.rotation}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[46.86, -8.01, 70.21]}
              ref={wheel1}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.68, 0.68, 0.68]}>
              <mesh geometry={nodes.wheel_Material009_0.geometry} material={nodes.wheel_Material009_0.material} />
              <mesh geometry={nodes.wheel_Material008_0.geometry} material={nodes.wheel_Material008_0.material} />
              <mesh geometry={nodes.wheel_Material004_0.geometry} material={nodes.wheel_Material004_0.material} />
              <mesh geometry={nodes.wheel_Chrome000_0.geometry} material={nodes.wheel_Chrome000_0.material} />
            </group>
            <group position={[46.63, -8.01, 70.14]} rotation={[2.53, 0.26, 0.18]} scale={[0.57, 0.57, 0.57]}>
              <mesh geometry={nodes.cal_Material010_0.geometry} material={nodes.cal_Material010_0.material} />
            </group>
            <group position={[0.66, 28.49, -30.26]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object000_Material003_0.geometry} material={materials['Material.003']} />
            </group>
            <group position={[0.67, 39.99, -113.51]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object018_emitbrake_0.geometry} material={materials.emitbrake} />
              <mesh geometry={nodes.object018_Material001_0.geometry} material={materials['Material.001']} />
            </group>
            <group position={[0.67, 21.18, 103.98]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object017_xenon_0.geometry} material={materials.xenon} />
            </group>
            <group position={[0.67, 20.71, 101.75]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object016_LightsFrontLed_0.geometry} material={materials.LightsFrontLed} />
            </group>
            <group position={[0.66, 39.69, 21]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object012_refl_0.geometry} material={materials.refl} />
            </group>
            <group position={[0.66, 38.45, 23.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object011_Yellow_0.geometry} material={materials.Yellow} />
            </group>
            <group position={[0.65, 44.81, -27.37]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object009_Glass_0.geometry} material={materials.Glass} />
            </group>
            <group position={[0.67, 9.84, 83.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object008_grills_0.geometry} material={materials.grills} />
            </group>
            <group position={[0.66, 22.53, -29.07]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object007_GreyElements_0.geometry} material={materials.GreyElements} />
            </group>
            <group position={[0.67, -5.5, -2.25]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object006_ChromeBLurred_0.geometry} material={materials.ChromeBLurred} />
            </group>
            <group position={[0.67, 1.77, -2.02]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object005_flack_0.geometry} material={materials.flack} />
            </group>
            <group position={[1.73, 24.72, -27.39]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object004_interiror_0.geometry} material={materials.interiror} />
            </group>
            <group position={[0.66, 24.22, -2.63]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object003_LightsGlassFront_0.geometry} material={materials.LightsGlassFront} />
            </group>
            <group position={[0.66, 22.34, -2.59]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object002_CarPaint_0.geometry} material={materials.CarPaint} />
            </group>
            <group position={[0.67, 4.23, -118.71]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object019_refd_0.geometry} material={nodes.object019_refd_0.material} />
            </group>
            <group position={[3.94, 26.2, -1.86]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object021_chromechr_0.geometry} material={materials.chromechr} />
              <mesh geometry={nodes.object021_logo_0.geometry} material={materials.logo} />
            </group>
            <group position={[0.67, 9.44, 107.98]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object010_detail_1_0.geometry} material={materials.detail_1} />
            </group>
            <group position={[0.67, 30.34, -114.62]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object014_Material005_0.geometry} material={materials['Material.005']} />
            </group>
            <group position={[0.67, 29.44, -114.74]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object015_Material006_0.geometry} material={materials['Material.006']} />
            </group>
            <group position={[0.67, 28.92, -110.77]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object020_refd_0.geometry} material={nodes.object020_refd_0.material} />
            </group>
            <group position={[0.67, -5.5, -2.25]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object013_glack_0.geometry} material={materials.glack} />
            </group>
            <group position={[-45.29, -8.01, 70.14]} ref={wheel2} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.68, 0.68, 0.68]}>
              <mesh geometry={nodes.wheel001_Material009_0.geometry} material={nodes.wheel001_Material009_0.material} />
              <mesh geometry={nodes.wheel001_Material008_0.geometry} material={nodes.wheel001_Material008_0.material} />
              <mesh geometry={nodes.wheel001_Material004_0.geometry} material={nodes.wheel001_Material004_0.material} />
              <mesh geometry={nodes.wheel001_Chrome000_0.geometry} material={nodes.wheel001_Chrome000_0.material} />
            </group>
            <group position={[-45.07, -8.01, 70.21]} rotation={[2.53, 0.26, 0.18]} scale={[-0.57, 0.57, 0.57]}>
              <mesh geometry={nodes.cal001_Material010_0.geometry} material={nodes.cal001_Material010_0.material} />
            </group>
            <group position={[-45.06, -8.01, -81.63]} rotation={[2.55, 0, 0]} scale={[-0.57, 0.57, 0.57]}>
              <mesh geometry={nodes.cal002_Material010_0.geometry} material={nodes.cal002_Material010_0.material} />
            </group>
            <group position={[-45.3, -8.01, -81.63]} ref={wheel3} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.68, 0.68, 0.68]}>
              <mesh geometry={nodes.wheel002_Material009_0.geometry} material={nodes.wheel002_Material009_0.material} />
              <mesh geometry={nodes.wheel002_Material008_0.geometry} material={nodes.wheel002_Material008_0.material} />
              <mesh geometry={nodes.wheel002_Material004_0.geometry} material={nodes.wheel002_Material004_0.material} />
              <mesh geometry={nodes.wheel002_Chrome000_0.geometry} material={nodes.wheel002_Chrome000_0.material} />
            </group>
            <group position={[46.63, -8.01, -81.63]} rotation={[2.55, 0, 0]} scale={[0.57, 0.57, 0.57]}>
              <mesh geometry={nodes.cal003_Material010_0.geometry} material={nodes.cal003_Material010_0.material} />
            </group>
            <group position={[46.86, -8.01, -81.63]} ref={wheel4} rotation={[-Math.PI / 2, 0, 0]} scale={[0.68, 0.68, 0.68]}>
              <mesh geometry={nodes.wheel003_Material009_0.geometry} material={nodes.wheel003_Material009_0.material} />
              <mesh geometry={nodes.wheel003_Material008_0.geometry} material={nodes.wheel003_Material008_0.material} />
              <mesh geometry={nodes.wheel003_Material004_0.geometry} material={nodes.wheel003_Material004_0.material} />
              <mesh geometry={nodes.wheel003_Chrome000_0.geometry} material={nodes.wheel003_Chrome000_0.material} />
            </group>
          </group>
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('../../car/scene.gltf')
