/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: aurelkillers1 (https://sketchfab.com/aurelkillers1)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/folding-table-878d6eca6ff14f84bccca081cc5f95a7
title: Folding Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../camp/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.Table} />
      </group>
    </group>
  )
}

useGLTF.preload('../../camp/scene.gltf')
