/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: YannisTH (https://sketchfab.com/YannisTH)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/camp-fire-3e1b91e633e64995b4023523edb3e237
title: Camp Fire
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes } = useGLTF('../../camp/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Wood_Wood_0.geometry} material={nodes.Wood_Wood_0.material} />
          <mesh geometry={nodes.Wood_Wood_0_1.geometry} material={nodes.Wood_Wood_0_1.material} />
          <mesh geometry={nodes.Wood_Wood_0_2.geometry} material={nodes.Wood_Wood_0_2.material} />
          <mesh geometry={nodes.Wood_Wood_0_3.geometry} material={nodes.Wood_Wood_0_3.material} />
          <mesh geometry={nodes.Wood_Wood_0_4.geometry} material={nodes.Wood_Wood_0_4.material} />
          <mesh geometry={nodes.Wood_Wood_0_5.geometry} material={nodes.Wood_Wood_0_5.material} />
          <mesh geometry={nodes.Wood_Wood_0_6.geometry} material={nodes.Wood_Wood_0_6.material} />
          <mesh geometry={nodes.Wood_Wood_0_7.geometry} material={nodes.Wood_Wood_0_7.material} />
          <mesh geometry={nodes.Wood_Wood_0_8.geometry} material={nodes.Wood_Wood_0_8.material} />
          <mesh geometry={nodes.Wood_Wood_0_9.geometry} material={nodes.Wood_Wood_0_9.material} />
          <mesh geometry={nodes.Wood_Wood_0_10.geometry} material={nodes.Wood_Wood_0_10.material} />
          <mesh geometry={nodes.Wood_Wood_0_11.geometry} material={nodes.Wood_Wood_0_11.material} />
          <mesh geometry={nodes.Stones_Stones_0.geometry} material={nodes.Stones_Stones_0.material} />
          <mesh geometry={nodes.Stones_Stones_0_1.geometry} material={nodes.Stones_Stones_0_1.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../camp/scene.gltf')
