/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: alexxx_xarchenko (https://sketchfab.com/alexxx_xarchenko)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tent-f6fef44f1e11487e8aec68123042cf03
title: Tent
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame , useThree } from '@react-three/fiber'
import * as THREE from 'three'

export default function Model(props) {
  const {sectionID} = props;
  const group = useRef()
  
  const camera = useThree((state) => state.camera);

  useFrame(()=>{
    sectionID === 4 ? camera.position.lerp(new THREE.Vector3(3, 0.8, 0),0.025):camera.position.lerp(new THREE.Vector3(3, 0.4, 0),0.025);
  });

  const { nodes } = useGLTF('../../tent/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -0.3]}>
        <group position={[0, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={nodes.defaultMaterial.material} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={nodes.defaultMaterial_1.material} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={nodes.defaultMaterial_2.material} />
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={nodes.defaultMaterial_3.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../tent/scene.gltf')
